language: python

# sudo false implies containerized builds
sudo: false

python:
  - 3.5

env:
  global:
    # List package dependencies for conda
    - CONDA_DEPS="pytest numpy scipy matplotlib seaborn"
    # package name for test invocation
    - PACKAGENAME="chiron"

before_install:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda create -n testenv python=$TRAVIS_PYTHON_VERSION
  - source activate testenv
  - conda install -c https://conda.anaconda.org/kne pybox2d
  - pip install requirements.txt

install:
- python setup.py install

script:
- pytest $PACKAGENAME