language: python

# sudo false implies containerized builds
sudo: false

python:
  - 3.5

before_install:
# Here we download miniconda and install the dependencies
- export MINICONDA=$HOME/miniconda
- export PATH="$MINICONDA/bin:$PATH"
- hash -r
- wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
- bash miniconda.sh -b -f -p $MINICONDA
- conda config --set always_yes yes
- conda update conda
- conda info -a
- conda env create -n testenv -f environment.yml
- conda install -n testenv python=3.5
- source activate testenv
- python --version
#- conda install -c https://conda.anaconda.org/kne pybox2d

install:
- source activate testenv
- python setup.py install

script:
- source activate testenv
- python --version
- python -m pytest --cov=.
- codecov