channels:
  - kne
dependencies:
  - numpy
  - pytest
  - numpy
  - scipy
  - matplotlib
  - seaborn
  - pybox2d
  - pyzmq
  - python=3.5
  - pip:
      - gym
      - codecov
      - pytest
      - pytest-cov
